"""Populate the HDI database from the curated `Medicine_data/` dataset.

Reads `entities.json` and `interactions.json`, rebuilds the `entities`,
`entity_aliases`, and `interactions` tables from scratch, and reports counts
per interaction class. All three classes (TCM-WM, WM-WM, TCM-TCM) are loaded;
the conflict-check endpoint consumes TCM-WM today and the rest are stored for
later.

Run from the `hdi-api/` directory:

    python seed.py

The database file (`hdi.db`) is gitignored and regenerated by this script, so
re-run it whenever the dataset changes.
"""

import json
import re
from pathlib import Path
from typing import Iterable

from database import Base, Entity, EntityAlias, Interaction, SessionLocal, engine

DATA_DIR = Path(__file__).parent / "Medicine_data"

# Entity fields that carry human-readable names we want to match free text against.
# `active_constituents` is intentionally excluded — constituents (e.g. "berberine")
# are not the herb itself and would cause false matches.
_NAME_FIELDS = ("preferred_name", "latin", "pinyin", "chinese")


def _variants(value: str) -> Iterable[str]:
    """Yield lowercased alias variants from one raw name string.

    Splits on "/" (several entities pack two names into one field, e.g. the
    pinyin "fuzi / wutou") and adds a parenthetical-stripped form so e.g.
    "bai guo (seed)" also matches "bai guo".
    """
    if not value:
        return
    for part in value.split("/"):
        part = part.strip()
        if not part:
            continue
        yield part.lower()
        stripped = re.sub(r"\(.*?\)", "", part).strip()
        if stripped and stripped.lower() != part.lower():
            yield stripped.lower()


def _aliases_for(entity: dict) -> set[str]:
    """All lowercased, de-duplicated alias strings for one entity."""
    aliases: set[str] = set()
    for field in _NAME_FIELDS:
        aliases.update(_variants(entity.get(field, "")))
    for name in entity.get("common_names", []) or []:
        aliases.update(_variants(name))
    aliases.discard("")
    return aliases


def seed() -> None:
    entities = json.loads((DATA_DIR / "entities.json").read_text(encoding="utf-8"))
    interactions = json.loads((DATA_DIR / "interactions.json").read_text(encoding="utf-8"))

    # Fail loudly on referential gaps rather than silently dropping rows.
    entity_ids = {e["entity_id"] for e in entities}
    dangling = [
        i["id"]
        for i in interactions
        if i["agent_a_id"] not in entity_ids or i["agent_b_id"] not in entity_ids
    ]
    if dangling:
        raise ValueError(f"Interactions reference unknown entity ids: {dangling}")

    # Rebuild from scratch so re-runs are idempotent.
    Base.metadata.drop_all(bind=engine)
    Base.metadata.create_all(bind=engine)

    db = SessionLocal()
    try:
        for e in entities:
            db.add(
                Entity(
                    entity_id=e["entity_id"],
                    preferred_name=e["preferred_name"],
                    type=e["type"],
                    drug_class=e.get("drug_class"),
                    rxnorm_id=e.get("rxnorm_id"),
                    latin=e.get("latin"),
                    pinyin=e.get("pinyin"),
                    chinese=e.get("chinese"),
                    common_names=json.dumps(e.get("common_names", []), ensure_ascii=False),
                    active_constituents=json.dumps(
                        e.get("active_constituents", []), ensure_ascii=False
                    ),
                )
            )
            for alias in _aliases_for(e):
                db.add(EntityAlias(alias=alias, entity_id=e["entity_id"]))

        for i in interactions:
            db.add(
                Interaction(
                    interaction_id=i["id"],
                    agent_a_id=i["agent_a_id"],
                    agent_b_id=i["agent_b_id"],
                    interaction_class=i["interaction_class"],
                    severity=i.get("severity"),
                    effect_direction=i.get("effect_direction"),
                    mechanism=i.get("mechanism"),
                    clinical_effect=i.get("clinical_effect"),
                    management=i.get("management"),
                    evidence_level=i.get("evidence_level"),
                    sources=json.dumps(i.get("sources", []), ensure_ascii=False),
                )
            )

        db.commit()

        # Report what landed.
        n_entities = db.query(Entity).count()
        n_aliases = db.query(EntityAlias).count()
        n_int = db.query(Interaction).count()
        by_class = {
            cls: db.query(Interaction).filter(Interaction.interaction_class == cls).count()
            for cls in ("TCM-WM", "WM-WM", "TCM-TCM")
        }
        print(f"Seeded {n_entities} entities, {n_aliases} aliases, {n_int} interactions.")
        print(f"  by class: {by_class}")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
